server.name: kibana
server.host: "0.0.0.0"
server.port: 5601

elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "changeme"

kibana.index: ".kibana"
kibana.defaultAppId: "discover"

# Security settings
xpack.security.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "your_encryption_key_here"

# Monitoring
xpack.monitoring.enabled: true
xpack.monitoring.ui.container.elasticsearch.enabled: true

# Advanced settings
logging:
  appenders:
    file:
      type: file
      fileName: /var/log/kibana/kibana.log
      layout:
        type: json
  root:
    appenders: [default, file]
    level: info

# Custom settings for Encore
newsfeed.enabled: false
telemetry.enabled: false
telemetry.optIn: false

# Data settings
data.autocomplete.valueSuggestions.timeout: 1000
data.search.timeout: 30000

# Visualization settings
visualization:loaderTimeout: 20000

# Console settings
console.enabled: true
console.proxyConfig:
  - match:
      protocol: "http:"
      host: "analytics-service"
      port: 3005
    timeout: 30000
  - match:
      protocol: "http:"
      host: "music-service"
      port: 3002
    timeout: 30000
  - match:
      protocol: "http:"
      host: "auth-service"
      port: 3001
    timeout: 30000